[workspace]
resolver = "2"
members = [
    "examples/add",
    "omniglot-lfi",
    "tests",
]

[workspace.metadata.crane]
name = "omniglot-lfi-workspace"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies.omniglot]
git = "https://github.com/omniglot-rs/omniglot"
rev = "bd8654b11ce47118d3158a08e83be2011eb02b01"
# path = "../omniglot/omniglot"
features = [ "std" ]

[workspace.dependencies.bindgen]
git = "https://github.com/omniglot-rs/rust-bindgen"
rev = "8c5d80549c02cd57905ced1e6b8ecebe2d92c7f5"
# path = "../rust-bindgen/bindgen"
