[workspace]
resolver = "2"
members = [
    "examples/add",
    "omniglot-lfi",
    "tests",
]

[workspace.metadata.crane]
name = "omniglot-lfi-workspace"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies.omniglot]
git = "https://github.com/omniglot-rs/omniglot"
rev = "b3c5ef8e1e40e2a466e926bcac1d989021833e38"
# path = "../omniglot/omniglot"
features = [ "std" ]

[workspace.dependencies.bindgen]
git = "https://github.com/omniglot-rs/rust-bindgen"
rev = "fffcf97244fc77c2cfa8d2290d740385f18021f1"
# path = "../rust-bindgen/bindgen"
