[workspace]
resolver = "2"
members = [
    "omniglot-lfi",
    "examples/add",
]

[workspace.metadata.crane]
name = "omniglot-lfi-workspace"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies.omniglot]
git = "https://github.com/omniglot-rs/omniglot"
rev = "fbaa9828fc3ab7e5ed3c0f85787c37618c65b883"
# path = "../omniglot"
features = [ "std" ]

[workspace.dependencies.bindgen]
git = "https://github.com/omniglot-rs/rust-bindgen"
rev = "6ac78b50e33ac7b68a845755cfdc2e2b60d22ff8"
# path = "../rust-bindgen/bindgen"
