wrapper_name = "Llhttp"

[functions.llhttp_settings_init]
fntab_id = 1

[functions.llhttp_init]
fntab_id = 2

[functions.llhttp_execute]
fntab_id = 3

[functions.llhttp_errno_name]
fntab_id = 4

[functions.llhttp_get_error_reason]
fntab_id = 5
