name: "Nix Flake Checks"

on:
  pull_request:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - uses: cachix/install-nix-action@v31
      with:
        # Helps with rate limits:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    # Builds all packages and runs other checks like linters:
    - run: nix flake check
