name: "Prebuild Example LFI Sandbox Binaries"

on:
  workflow_dispatch:
    inputs:
      create-release:
        description: >-
          Create a GitHub release with the prebuilt binaries
          attached. If `false`, the binaries will still be uploaded as
          workflow outputs.
        required: true
        type: boolean
        default: true

permissions:
  # Required to create a release
  contents: write

jobs:
  prebuild-examples:
    runs-on: ubuntu-latest

    steps:
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake llvm

    - name: Install LFI clang toolchain
      run: |
        pushd "${RUNNER_TEMP}"
        wget -q https://github.com/lfi-project/lfi/releases/download/v0.11/x86_64-lfi-clang.tar.gz
        sha256sum -c <(echo "321fc937383aaa7561a2251b476474d4a41efd16cf5cda264b0248849b6c788b  x86_64-lfi-clang.tar.gz")
        tar -xf x86_64-lfi-clang.tar.gz
        echo "LFI_CLANG_TOOLCHAIN=$PWD/x86_64-lfi-clang/lfi-bin" >> $GITHUB_ENV
        popd

    - name: Install native clang toolchain
      run: |
        pushd "${RUNNER_TEMP}"
        wget -q https://github.com/lfi-project/lfi/releases/download/v0.11/x86_64-native-clang.tar.gz
        sha256sum -c <(echo "8bb7c8844f839912af67f0f130f0e261d1a49e330f14aaeaf872cc50053c0cb9  x86_64-native-clang.tar.gz")
        tar -xf x86_64-native-clang.tar.gz
        echo "NATIVE_CLANG_TOOLCHAIN=$PWD/x86_64-native-clang/lfi-bin" >> $GITHUB_ENV
        popd

    - uses: actions/checkout@v6
      with:
        submodules: true

    - name: Build brotli example
      run: |
        pushd ./examples/brotli/og_brotli_lfi
        ./build.sh "${LFI_CLANG_TOOLCHAIN}" "${NATIVE_CLANG_TOOLCHAIN}"
        popd

    - name: Build libpng example
      run: |
        pushd ./examples/libpng/og_libpng_lfi
        ./build.sh "${LFI_CLANG_TOOLCHAIN}" "${NATIVE_CLANG_TOOLCHAIN}"
        popd

    - name: Build libsodium example
      run: |
        pushd ./examples/sodium/og_sodium_lfi
        ./build.sh "${LFI_CLANG_TOOLCHAIN}" "${NATIVE_CLANG_TOOLCHAIN}"
        popd

    - name: Upload prebuilt examples as Workflow Artifacts
      uses: actions/upload-artifact@v4

      # skip when running locally with `act`
      if: ${{ !env.ACT }}

      with:
        name: prebuilt-examples
        path: |
          ./examples/brotli/og_brotli_lfi/build/og_brotli_lfi.tar.gz
          ./examples/libpng/og_libpng_lfi/build/og_libpng_lfi.tar.gz
          ./examples/libpng/og_sodium_lfi/build/og_sodium_lfi.tar.gz

    - name: Determine GitHub Release Variables
      id: gh_release_vars
      run: |
        GITHUB_SHA="${{ github.sha }}"
        GITHUB_SHA_SHORT="${GITHUB_SHA:0:14}"
        echo "sha_short=${GITHUB_SHA_SHORT}" >> $GITHUB_OUTPUT
        echo "release_ts=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

    - name: Publish prebuilt examples as GitHub pre-release
      uses: softprops/action-gh-release@v2

      # only run if requested, and skip when running locally with `act`
      if: ${{ inputs.create-release && !env.ACT}}

      with:
        name: prebuilt-examples-${{ steps.gh_release_vars.outputs.release_ts }}-${{ steps.gh_release_vars.outputs.sha_short }}
        tag_name: prebuilt-examples-${{ steps.gh_release_vars.outputs.release_ts }}-${{ steps.gh_release_vars.outputs.sha_short }}
        body: >-
          Pre-built LFI sandbox binaries for the example libraries
          included in this repository. Automatically built and
          published through GitHub Actions.
        prerelease: true
        files: |
          ./examples/brotli/og_brotli_lfi/build/og_brotli_lfi.tar.gz
          ./examples/libpng/og_libpng_lfi/build/og_libpng_lfi.tar.gz
          ./examples/sodium/og_sodium_lfi/build/og_sodium_lfi.tar.gz
